### ISSUE TITLE
Colors off in GR

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#781]
The colors passed to GR appear to not be parsed correctly. MWE:
```julia
using Plots; gr(grid = false, ms = 150, legend = false, msw = 0)
scatter([1,2],[1,1], c =["#5fafaf", "#7aa6da"], ms = 150, ylim = [0,2], xlim = [0,3])
```
![skaermbillede 2017-04-27 kl 12 10 19](https://cloud.githubusercontent.com/assets/8429802/25478718/89c2422a-2b42-11e7-8b61-30d9e5cfa96e.png)
```julia
pyplot(grid = false, ms = 150, legend = false, msw = 0)
scatter([1,2],[1,1], c =["#5fafaf", "#7aa6da"], ms = 150, ylim = [0,2], xlim = [0,3])
```
![skaermbillede 2017-04-27 kl 12 11 20](https://cloud.githubusercontent.com/assets/8429802/25478758/a8f0854e-2b42-11e7-8446-3314ae7b3dc7.png)

Using an RGB color picker confirms that the colors are correct with pyplot.
@jheinen are you aware of this?

**Comment by mkborregaard** [comment]
Arose here: https://github.com/JuliaGraphics/Colors.jl/issues/286

**Comment by jheinen** [comment]
I'm currently out of office - but I'll try to fix this ASAP ...

**Comment by oxinabox** [comment]
Black is wrong too BTW.
I noticed this about a month ago, and I concluded it was an issue with the GR framework,
and I may have been a bad Open Source citizen and failed to make a bug report as I was busy.

![image](https://cloud.githubusercontent.com/assets/5127634/25490691/2679ef48-2ba0-11e7-8f15-07311dc63e50.png)

Ms-Paint is telling me that the blacks in the top (gr) image is `#00002D`
which seems reasonable.

Really messes with you when you are trying to do color/perception related science with them.

**Comment by jheinen** [comment]
The problem is fixed in https://github.com/jheinen/gr/commit/ae40c99eeb499e1909799ae1291727bd68a43321 . I will provide new GR run-time binaries tomorrow ...

**Comment by mkborregaard** [comment]
That's amazing!

**Comment by jheinen** [comment]
The new binaries (for GR master) are ready-to-install:
```
ENV["GRDIR"]=""
Pkg.build("GR")
```

**Comment by mkborregaard** [comment]
This did solve the initial issue with the blue colors. But it didn't solve the black issue. Instead (using in Juno), `scatter([1,2],[1,1], c =["black", "#000000"], ms = 150, ylim = [0,2], xlim = [0,3])` resulted in two gray circles (rgb(68,68,68)), calling `gui()` to view in gksterm gave rgb(86,86,86)! Even more strangely, after calling the above twice, I tried to repeat the blue circles with `scatter([1,2],[1,1], c =["#5fafaf", "#7aa6da"], ms = 150, ylim = [0,2], xlim = [0,3])` and got 
![skaermbillede 2017-04-28 kl 10 53 26](https://cloud.githubusercontent.com/assets/8429802/25521694/eec0bf26-2c00-11e7-9c0c-964f5a9d5bf5.png)

**Comment by jheinen** [comment]
I can not reproduce the problem. Are you really using the GR master branch with the latest run-time (see previous post) ?

<img width="573" alt="screen shot 2017-04-28 at 17 06 38" src="https://cloud.githubusercontent.com/assets/5718244/25534766/315a7d2a-2c35-11e7-94b4-0232c7c80114.png">

**Comment by mkborregaard** [comment]
Yes:
<img width="761" alt="skaermbillede 2017-04-29 kl 13 20 38" src="https://cloud.githubusercontent.com/assets/8429802/25555135/c27f3fe4-2cde-11e7-9a6c-6463eada39ea.png">
<img width="727" alt="skaermbillede 2017-04-29 kl 13 20 56" src="https://cloud.githubusercontent.com/assets/8429802/25555136/c56837d8-2cde-11e7-9408-90259070bd02.png">
```
versioninfo()
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by jheinen** [comment]
This is weird - I can't reproduce it.

I suspect there is a caching problem with the downloaded tar-file.
Could you please verify the `libGR.so` checksum?
```julia
using GR
libgr = joinpath(ENV["GRDIR"], "lib", "libGR.so")
println(readstring(pipeline(`sum $libgr`)))
```
The output should start with
```
48021 11164 ...
```

**Comment by mkborregaard** [comment]
48021 11164 /Users/michael/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so

**Comment by jheinen** [comment]
No idea. I used a fresh Julia 0.5.1 installation with only 1 package (GR) installed. Could you please try this (GR-only) scenario:
```julia
using GR
setmarkersize(20)
setmarkertype(-21)
setmarkercolorind(Int(inqcolorfromrgb(0.373, 0.686, 0.686)))
polymarker([0.25], [0.5])
setmarkercolorind(Int(inqcolorfromrgb(0.478, 0.650, 0.855)))
polymarker([0.75], [0.5])
```

**Comment by mkborregaard** [comment]
That appears to work as expected - using the colors `Int(inqcolorfromrgb(0, 0, 0))` also creates the expected complete black. Plots/GR integration issue? I am on Plots master.

**Comment by mkborregaard** [comment]
@oxinabox can you try
```julia
Pkg.checkout("GR")
ENV["GRDIR"]=""
Pkg.build("GR")
```
and then recreate your issue? It'd be good to know if this is only on my system.

**Comment by daschw** [comment]
Here is what I get, when I try to plot the above example:
(I am on Plots and GR master and I did
```
Pkg.checkout("GR")
ENV["GRDIR"]=""
Pkg.build("GR")
```
When I plot for the first time in Juno I get this:
![gr_black_juno_screenshot1](https://cloud.githubusercontent.com/assets/16589944/25577000/5c255806-2e63-11e7-906d-08782559137a.png)

However, saving this file changes the colors to grey:
![gr_black_juno](https://cloud.githubusercontent.com/assets/16589944/25577012/7e82c640-2e63-11e7-9b35-7ad4d75279d1.png)

Plotting the same Plot twice also turns the colors to grey:
![gr_black_juno_screenshot2](https://cloud.githubusercontent.com/assets/16589944/25577030/9b3fbb1c-2e63-11e7-9e8d-52c63021a2f8.png)

If I do this in the julia REPL the same thing happens
1st plot command: black colors
saving as png: grey colors
2nd plot command: grey colors

This is not only happening with black:
1st plot in Juno:
![gr_blue_juno_screenshot1](https://cloud.githubusercontent.com/assets/16589944/25577056/c67ce6f6-2e63-11e7-8aa0-3cbcaa40fede.png)
 
Saved png:
![gr_blue_juno](https://cloud.githubusercontent.com/assets/16589944/25577069/d88116ce-2e63-11e7-879a-0d176a753385.png)

2nd plot in Juno:
![gr_blue_juno_screenshot2](https://cloud.githubusercontent.com/assets/16589944/25577158/7e51cefe-2e64-11e7-9b08-cac018a1253c.png)

**Comment by daschw** [comment]
It seems like once a color has been used, it is turned to grey:
![gr_1color_screenshot](https://cloud.githubusercontent.com/assets/16589944/25577665/3e7b7628-2e68-11e7-8dae-7c74e6baf16e.png)

![gr_2colors_screenshot](https://cloud.githubusercontent.com/assets/16589944/25577627/d3060944-2e67-11e7-907e-eaf6af90e4d0.png)

**Comment by mkborregaard** [comment]
Confirmed

**Comment by daschw** [comment]
From the REPL, however, you can add new series like
```julia
using Plots
plot(rand(10))
plot!(rand(10))
```
without modifying the existing series color.
In Juno this would turn the existing series color to grey like in the screenshots above.
In both cases saved images are all grey.

**Comment by jheinen** [comment]
There was still a stupid bug, but the problem(s) should be fixed with the latest run-time:
```julia
ENV["GRDIR"]=""
Pkg.build("GR")
```

**Comment by mkborregaard** [comment]
Perfect - that worked! :-)

**Comment by mkborregaard** [comment]
@daschw by the way - how do you get that nice projects panel to show in Juno?

**Comment by daschw** [comment]
Yep, now it works again for me!

**Comment by daschw** [comment]
@mkborregaard in the menu bar: `View`->`Toggle Tree View`
